rules:
  example:
    unrestrictedMessage: You can %s ex1 now.
    restrictedMessage: 'You cannot %1 %3 after XP level %4'
    actions:
    - CRAFT
    - PICKUP
    - USE
    worlds:
    - world
    excludeWorlds:
    - world_nether
    XPMin: 0
    XPMax: 2
    items:
    - '268'
    - '5.2'
  example2:
    unrestrictedMessage: You can %s ex2 now.  
    restrictedMessage: 'You cannot %1 %4 until after XP level %3'
    actions:
    - CRAFT
    - PICKUP
    - USE
    worlds:
    - world
    excludeWorlds:
    - world_nether
    XPMin: 5
    XPMax: 
    items:
    - '276'
    - '278'
