rules:
    WoodenWeapons:
        messages:
            unrestricted: 'use wooden equipment'
            restricted: 'no wooden equipment after level 2'
        actions: [CRAFT, PICKUP, USE]
        xp:
            max: 2
        items:
            access: [268, 268, 270, 271]
    StoneWeapons:
        messages:
            unrestricted: 'use stone equipment'
            restricted: 'no stone equipment until level 2'
        actions:
        - CRAFT
        - PICKUP
        - USE
        worlds:
            applyto:
            - world
        xp:
            min: 2
        items:
            restrict:
            - '272'
            - '273'
            - '274'
            - '275'
    diamondWeapons:
        messages:
            unrestricted: 'use diamond weapons and tools'
            restricted: 'no diamond weapons/tools until level 5'
        actions:
        - CRAFT
        - PICKUP
        - USE
        worlds:
            applyto:
            - world
        xp:
            min: 5 
        items:
            access:
            - '276'
            - '277'
            - '278'
            - '279'
            restrict:
            - 280
manualRules:
    sticksOnly:
        actions: [USE]
        explicit: true
        items: [280]
areaRules:
    pvpZone:
        world: world
        ne: [-180, 75, 204]
        sw: [-167, 68, 186]
        entrance: [sticksOnly]
        exit: [sticksOnly]