name: ItemRules
main: com.github.mineGeek.ItemRules.ItemRules
version: 1.0.3
softdepend: [mcMMO, Factions, Vault]
commands:
    rules:
        description: List of what rules are currently affecting you
        aliases: [ir]
        usage: /rules
    apply:
        description: Attach a rule to a player
        aliases: [irapply]
        usage: /apply [playerName] [ruleName]
        permission: ItemRules.apply
        permission-message: 'You lack permissions for this command'        
    revoke:
        description: Remove a manual rule from a player
        aliases: [irrevoke]
        usage: /revoke [playerName] [ruleName]
        permission: ItemRules.revoke
        permission-message: 'You lack permissions for this command'       