name: ItemRules
main: com.github.mineGeek.ItemRules.ItemRules
version: 1.0.0
softdepend: [mcMMO, Factions, Valut]
commands:
    can:
        description: List of what you can do at your level
        aliases: [ircan]
        usage: /can [all|now|next]
    cant:
        description: a list of what you can't do
        aliases: [ircant]
        usage: /cant [all|now|next]
    apply:
        description: Applies a (manual) rule to a player
        aliases: [irapply]
        usage: /apply player ruleName
        permission: itemRules.admin.apply
        permisson-message: You don't have permission for this
    revoke:
        description: removes a (manual) rule from player
        aliases: [irrevoke]
        usage: /revoke playerName ruleName
        permission: itemRules.admin.revoke
        permission-message: You lack the skillz for this